- set_fact:
    download_dir: "{{ role_path }}/files"
    tmp_dir: "{{ tmp_prefix }}/ruby-{{ ruby_version }}"
    ruby_dir: "{{ urls[ruby_version].source.dir }}"
    ruby_url: "{{ urls[ruby_version].source.url }}"
    ruby_hash: "{{ urls[ruby_version].source.hash }}"
    ruby_filename: "{{ urls[ruby_version].source.file }}"

- set_fact:
    ruby_home: "{{ prefix }}/{{ ruby_dir }}"
    ruby_archive_temp_path: "{{ tmp_dir }}/{{ ruby_filename }}"
    ruby_archive_download_path: "{{ download_dir }}/{{ ruby_filename }}"
    ruby_temp_path: "{{ tmp_dir }}/{{ ruby_dir }}"

- name: "Create Directories"
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ tmp_dir }}"
    - "{{ ruby_home }}"

- name: "Install GCC C++"
  yum:
    name: "gcc-c++"
    state: present

- name: "Create Download Directory on control server: {{ download_dir }}"
  delegate_to: 127.0.0.1
  file:
    path: "{{ download_dir }}"
    state: directory

- name: "Download Ruby archive to control server Download Path: {{ ruby_archive_download_path }}"
  delegate_to: 127.0.0.1
  get_url:
    url: "{{ ruby_url }}"
    dest: "{{ ruby_archive_download_path }}"
    checksum: "sha256:{{ ruby_hash }}"

- name: "Copy Ruby archive to Temporary Path: {{ ruby_archive_temp_path }}"
  copy:
    src: "{{ ruby_archive_download_path }}"
    dest: "{{ ruby_archive_temp_path }}"

- name: "Extract Ruby archive to Directory: {{ tmp_dir }}"
  unarchive:
    src: "{{ ruby_archive_temp_path }}"
    dest: "{{ tmp_dir }}"
    remote_src: yes


- name: "Install Ruby Dependencies"
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - git-core
    - zlib
    - zlib-devel
    - gcc-c++
    - patch
    - readline
    - readline-devel
    - libyaml-devel
    - libffi-devel
    - openssl-devel
    - make
    - bzip2
    - autoconf
    - automake
    - libtool
    - bison
    - curl
    - sqlite-devel

- name: "Compile Ruby"
  shell: "./configure  --prefix {{ ruby_home }}"
  args:
    chdir: "{{ ruby_temp_path }}"

- shell: "make"
  args:
    chdir: "{{ ruby_temp_path }}"

- shell: "make install"
  args:
    chdir: "{{ ruby_temp_path }}"

- name: "Install Ruby environment variables"
  template:
    src: "ruby.sh.j2"
    dest: "/etc/profile.d/ruby.sh"
    mode: 0644


- name: "Update Gem"
  shell: "source /etc/profile.d/ruby.sh && gem update --system"


- name: "Clean Temporary files"
  file:
    path: "{{ tmp_prefix }}"
    state: absent

- name: "Fix Permissions"
  shell: "{{ item }}"
  args:
    chdir: "{{ prefix }}"
  with_items:
    - "chown -R root:root ."
    - "find . -perm -u+r -exec chmod a+r {} \\;"
    - "find . -perm -u+w -exec chmod a+w {} \\;"
    - "find . -perm -u+x -exec chmod a+x {} \\;"

